// DO NOT MODIFY DIRECTLY! This file is generated by bin/build-routes,
// so if you need to regenerate, run that command.
'use strict';

const reactPathRegExp = new RegExp(
  '^(/404|/about/maps/s|/contact|/contact/sales|/contact/support|/industries/agriculture|/industries/business-intelligence|/industries/drones|/industries/government|/industries/logistics|/industries/media|/industries/outdoors|/industries/real-estate|/industries/transportation|/industries/travel|/install/android/add|/install/android/complete|/install/android|/install/android/permission|/install|/install/ios/cocoapods-add|/install/ios/cocoapods-complete|/install/ios/cocoapods-permission|/install/ios/cocoapods|/install/ios/download-add|/install/ios/download-complete|/install/ios/download-permission|/install/ios/download|/install/ios|/install/js/bundler-add|/install/js/bundler-complete|/install/js/bundler-install|/install/js/cdn-add|/install/js/cdn-complete|/install/js/cdn-install|/install/js|/navigation-sdk|/pricing|/signin|/signup|/use-cases/asset-tracking)'
);

function isReactPage(rootRelativePath) {
  // Home page
  if (rootRelativePath === '/') return true;
  // All the other pages
  if (reactPathRegExp.test(rootRelativePath)) {
    return true;
  }
  return false;
}

module.exports = isReactPage;
