/* @flow */
/* eslint-disable */
// DO NOT MODIFY DIRECTLY!
// This file is generated by bin/build-svgs.
// Please read https://github.com/mapbox/www2.mapbox.com/blob/dev-pages/CONTRIBUTING.md#svgs.
import React from 'react';
export class DeviceAndroid extends React.Component {
  props: SvgProps;
  shouldComponentUpdate() {
    return false;
  }
  render() {
    return React.createElement(
      'svg',
      {
        role: this.props.role ? this.props.role : 'img',
        focusable: 'false',
        'aria-labelledby': 'svg-title-DeviceAndroid',
        className: this.props.className,
        style: this.props.style,
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 350 676'
      },
      React.createElement('title', { id: 'svg-title-DeviceAndroid' }, this.props.title),
      React.createElement('title', null, 'android'),
      React.createElement('path', {
        d: 'M62.001 0h226c60 0 60 26.863 60 60v556c0 33.137 0 59.167-60 60h-226c-60 0-60-26.863-60-60V60c0-33.136-.001-60 60-60z',
        fill: '#ddd',
        fillRule: 'evenodd'
      }),
      React.createElement('path', {
        d: 'M346 614.167c0 33.137 2.001 60-60 60H64c-61.999 0-60-26.863-60-60v-552c0-33.137-1.999-60.012 60-60h222c62.001-.666 60 26.863 60 60z',
        fill: '#fff'
      }),
      React.createElement('path', {
        d: 'M214 647.98c0-6.524 0-11.813-11.813-11.813h-59.375C131 636.167 131 641.457 131 647.98v.375c0 6.523 0 11.812 11.813 11.812h59.375c11.812 0 11.812-5.29 11.812-11.813z',
        fill: '#fff',
        stroke: '#a0a0a0',
        strokeMiterlimit: '10',
        strokeWidth: '2',
        opacity: '.2'
      }),
      React.createElement('circle', { cx: '118.001', cy: '15.167', r: '7.167', fill: '#5b5b5b' }),
      React.createElement('circle', { cx: '228', cy: '15.167', r: '7.167', fill: '#5b5b5b' }),
      React.createElement('circle', { cx: '245', cy: '15.167', r: '7.167', fill: '#5b5b5b' }),
      React.createElement('circle', { cx: '287', cy: '21.167', r: '7.167', fill: '#5b5b5b' }),
      React.createElement('circle', { cx: '287', cy: '21.167', r: '4', fill: '#6d6d6d' }),
      React.createElement('circle', { cx: '287', cy: '21.167', r: '1', fill: '#5b5b5b' }),
      React.createElement('path', {
        d: 'M215 18.667a3.5 3.5 0 0 1-3.5 3.5h-73a3.5 3.5 0 0 1-3.5-3.5 3.5 3.5 0 0 1 3.5-3.5h73a3.5 3.5 0 0 1 3.5 3.5zM2 214.167a1 1 0 0 1-1 1 1 1 0 0 1-1-1v-110a1 1 0 0 1 1-1 1 1 0 0 1 1 1zM350 213.167a1 1 0 0 1-1 1 1 1 0 0 1-1-1v-58a1 1 0 0 1 1-1 1 1 0 0 1 1 1z',
        fill: '#ddd'
      }),
      React.createElement('rect', {
        x: '17',
        y: '60.167',
        width: '318',
        height: '557',
        rx: '5',
        ry: '5',
        fill: '#7e7e7e'
      })
    );
  }
}
